apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  ports:
  - port: 3306                      # Service port
    targetPort: 3306                # Container port
    protocol: TCP
    name: mysql
  selector:
    app: mysql
  type: ClusterIP                   # Exposes the service within the cluster
