apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi                # Specify the storage size you need
  storageClassName: ebs-sc     # Reference the EBS StorageClass created earlier
